# Generated by Django 5.2 on 2025-05-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
    ]
